name: Post Main Workflow

permissions:
  id-token: write # This is required by image-builder
  contents: read # This is required by image-builder

on:
  push:
    branches:
      - main

jobs:
  get-sha:
    name: Get manager SHA
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: get-sha
        uses: ./.github/actions/get-latest-sha

  #############################################
  # Performance tests
  # Run on: AWS
  #############################################

  istio-performance-test:
    name: Istio performance test
    runs-on: ubuntu-latest
    needs: [ get-sha ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/perf-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manager_image: "europe-docker.pkg.dev/kyma-project/prod/istio/main/istio-manager:${{ needs.get-sha.outputs.sha }}"
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_project_name: ${{ vars.GARDENER_PROJECT_NAME }}
          gardener_provider: aws
