name: Post Main Workflow

permissions:
  id-token: write # This is required by image-builder
  contents: read # This is required by image-builder

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "tests/performance/**"
      - "OWNERS"
      - "CODEOWNERS"
      - "sec-scanners-config.yaml"
      - "external-images.yaml"
      - ".reuse/**"

jobs:
  istio-performance-test:
    name: Istio performance test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/perf-test-gardener
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manager_image: "europe-docker.pkg.dev/kyma-project/prod/istio/main/istio-manager:3830383b16bcc14fc6f10abf3c8e079857286971"
          gardener_secret: ${{ secrets.GARDENER_TOKEN }}
          gardener_project_name: ${{ vars.GARDENER_PROJECT_NAME }}
          gardener_provider: aws

