name: 'Get latest Istio Manager SHA'
description: 'Get latest SHA of main build executed for Istio manager'
outputs:
  sha:
    description: 'SHA of the latest Istio Manager main build'
    value: ${{ steps.get-sha.outputs.sha }}
runs:
  using: "composite"
  steps:
    - name: Get SHA from latest run of main workflow triggered by push
      id: get-sha
      uses: actions/github-script@v7
      with:
        script: |
          core.setOutput('sha', 'e3b34272fa0e645ff9641fe720f84daaa77fd276');
